// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinuG5jCxpC13CCC2nf3_G6sxxfiHCGng',
    appId: '1:436748342271:web:d51312008912f89dc70dca',
    messagingSenderId: '436748342271',
    projectId: 'ds304-966e6',
    authDomain: 'ds304-966e6.firebaseapp.com',
    databaseURL: 'https://ds304-966e6-default-rtdb.firebaseio.com',
    storageBucket: 'ds304-966e6.appspot.com',
    measurementId: 'G-02P657473J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRz7eXAZLTcFih3qoTbMN6cpDuF6J-PU',
    appId: '1:436748342271:android:cf7ac828cd269788c70dca',
    messagingSenderId: '436748342271',
    projectId: 'ds304-966e6',
    databaseURL: 'https://ds304-966e6-default-rtdb.firebaseio.com',
    storageBucket: 'ds304-966e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVd9gIXES0e8YEIwOw0u9SuBjtdeyfNw0',
    appId: '1:436748342271:ios:310f2e6e9003ece0c70dca',
    messagingSenderId: '436748342271',
    projectId: 'ds304-966e6',
    databaseURL: 'https://ds304-966e6-default-rtdb.firebaseio.com',
    storageBucket: 'ds304-966e6.appspot.com',
    iosBundleId: 'com.example.ds304',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVd9gIXES0e8YEIwOw0u9SuBjtdeyfNw0',
    appId: '1:436748342271:ios:fa4e3df678df91dbc70dca',
    messagingSenderId: '436748342271',
    projectId: 'ds304-966e6',
    databaseURL: 'https://ds304-966e6-default-rtdb.firebaseio.com',
    storageBucket: 'ds304-966e6.appspot.com',
    iosBundleId: 'com.example.ds304.RunnerTests',
  );
}
